# Generated by Django 3.1.2 on 2020-10-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(choices=[('Go', 'Go'), ('Javascript', 'Javascript'), ('Java', 'Java'), ('Python', 'Python'), ('React', 'React'), ('Ruby', 'Ruby')], max_length=20)),
                ('location', models.CharField(choices=[('Beijing', 'Beijing'), ('Chicago', 'Chicago'), ('London', 'London'), ('Paris', 'Paris'), ('Phoenix', 'Phoenix'), ('San Francisco', 'San Francisco')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
